

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=comments_db
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - shortener-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comments_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./migrations/001_create_comments.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shortener-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ./postgres_data  # Явный путь относительно docker-compose.yml
    #   o: bind

#  redis_data:

networks:
  shortener-network:
    driver: bridge